package net.wfoas.gh.omapi;

public enum GHItemType{
	ARMOR_HELMET,
	ARMOR_CHESTPLATE,
	ARMOR_LEGGINGS,
	ARMOR_BOOTS,
	TOOL_SHOVEL,
	WEAPON_SWORD,
	TOOL_PICKAXE,
	TOOL_AXE,
	TOOL_HOE,
	TOOL_FLINTANDSTEEL,
	TOOL_FISHING_ROD,
	WEAPON_BOW,
	TOOL_SHEARS;
}